# GitHub Actions Documentation: https://docs.github.com/en/actions

name: "build"

on:
  push:
    branches:
      - "main"
    tags:
      - "*"
  pull_request:
    branches:
      - "main"

# Cancels all previous workflow runs for the same branch that have not yet completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  COMPOSER_ROOT_VERSION: "1.99.99"
  PHP_CS_FIXER_IGNORE_ENV: 1

jobs:
  ci:
    name: "Coding standards"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v4"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "latest"
          coverage: "none"

      - name: Install dev vendor
        run: make vendor

      - name: Tests
        run: make test

      - name: PHPStan
        id: phpstan
        run: make apply-phpstan

      - name: Security
        id: security
        run: make security

      - name: PHP Mess Detector
        id: phpmd
        run: make apply-phpmd

      - name: PHP-cs-fixer
        id: phpcsfixer
        run: make check-php-cs

      - name: PHPCPD
        id: phpcpd
        run: make apply-phpcpd
